export const GET_RECIPES = 'GET_RECIPES';
export const GET_RECIPES_SUCCESS = 'GET_RECIPES_SUCCESS';
export const GET_RECIPES_ERROR = 'GET_RECIPES_ERROR';
export const GET_CHEFS = 'GET_CHEFS';
export const GET_CHEFS_SUCCESS = 'GET_CHEFS_SUCCESS';
export const GET_CHEFS_ERROR = 'GET_CHEFS_ERROR';